---
title: "Heatmap metabolic markers in healthy SSc"
author: "Alex Matei"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document: 
    toc: true
    toc_float: true
    toc_depth: 4
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE,results='hide'}
source("data_preprocessing/common/config.R")
knitr::opts_chunk$set(warning = FALSE, message = FALSE, eval=FALSE) 
```

```{r load data, eval=TRUE}

dir<- c(project_path("IMC_metabolic_analysis_AEM"))

dir_r <- "data_preprocessing/common"

source(file.path(dir_r, "get_ts_rightformat_fx.R"))

ts <- get_ts_rightformat()
ptm <- proc.time()

cat("This document was created with the time stamp",ts)

library(tidyverse)
library(imcRtools)
library(SpatialExperiment)
library(scuttle)
library(CATALYST)
library(dittoSeq)
library(ggpubr)
library(rstatix)
library(ggstatsplot)
library(viridis)

spe<-readRDS(paste0(dir,"/Datasets/spe20250127122004.rds"))

source(file.path(dir_r, "output_dir_svg_plots_fx.R"))
output_dir <- output_dir_svg_plots_fx(ts)

```

# Prepare spe for analysis

```{r prep spe, eval=TRUE, cache=TRUE}
# Create a new data frame with all the colData of the spe object - to recode the patient_id column

metadata <- colData(spe)

# add a new column to metadata called Donor where you recode the patient_id column
# the elements starting with NH should be called Healthy1, Healthy2, etc.
# the elements starting with SSc should be called SSc1, SSc2, etc.
metadata$Donor <- dplyr::recode(metadata$patient_id,
                                     Healthy1="Healthy1",
                                     Healthy2="Healthy2", 
                                     SSc1="SSc1",
                                     SSc2="SSc2",
                                     SSc3="SSc3",
                                     SSc4="SSc4",
                                     SSc5="SSc5",
                                     SSc6="SSc6",
                                     SSc7="SSc7",
                                     SSc8="SSc8",
                                     Healthy3="Healthy3",
                                     Healthy4="Healthy4",
                                     SSc9="SSc9",
                                     Healthy5="Healthy5",
                                     Healthy6="Healthy6",
                                     Healthy7="Healthy7")

metadata$Disease <- dplyr::recode(metadata$indication,
                                  NH="Healthy",
                                  SSc="SSc")

metadata$ILD <- dplyr::recode(metadata$ILD,
                                     healthy="healthy",
                                     "1"="ILD", 
                                     "0"="no ILD")

metadata$Arthritis[is.na(metadata$Arthritis)] <- "no arthritis"

# Assign the new column in metadata to the spe object
spe$Donor <- metadata$Donor
spe$ILD <- metadata$ILD
spe$Arthritis <- metadata$Arthritis
spe$Disease <- metadata$Disease

names(colData(spe))[which(names(colData(spe))=="Skin.progression.at.biopsy")]="Progression_skin"
names(colData(spe))[which(names(colData(spe))=="Subtype.(dc/lc)")]="Subtype_dc_lc"

met_markers <- c("Glut1",
                 "HK1",
                 "PFKL1",
                 "PKM2",
                 "LDHA",
                 "GAPDH",
                 "CS",
                 "OGDH",
                 "ATP5A",
                 "SDHA",
                 "CD98",
                 "ACAC",
                 "CPT1a",
                 "G6PD",
                 "p_mTOR",
                 "pAMPK",
                 "NOX4",
                 "HIF1a",
                 "PGC-1a",
                 "TFAM",
                 "NRF2_p")

glycolysis_markers <- c("Glut1",
                 "HK1",
                 "PFKL1",
                 "PKM2",
                 "LDHA",
                 "GAPDH")

no_met_markers <- setdiff(rownames(spe),met_markers) 
rowData(spe)$use_channel_met_markers <- rownames(spe) %in% met_markers
rowData(spe)$use_channel_glyc_markers <- rownames(spe) %in% glycolysis_markers

# define clinical categories
clinical_cat <- c("Disease","Progression_skin", "Arthritis", "DU.history", "ILD", "Subtype_dc_lc", "Early.or.not")

spe[[clinical_cat[1]]] <- factor(spe[[clinical_cat[1]]], levels = c("Healthy", "SSc"))
spe[[clinical_cat[2]]] <- factor(spe[[clinical_cat[2]]], levels = c("healthy", "progressive", "stable"))
spe[[clinical_cat[3]]] <- factor(spe[[clinical_cat[3]]], levels = c("healthy","arthritis","no arthritis"))
spe[[clinical_cat[4]]] <- factor(spe[[clinical_cat[4]]], levels = c("healthy","DU history","no DU history"))
spe[[clinical_cat[5]]] <- factor(spe[[clinical_cat[5]]], levels = c("healthy","ILD","no ILD"))
spe[[clinical_cat[6]]] <- factor(spe[[clinical_cat[6]]], levels = c("healthy","dcSSc","lcSSc"))
spe[[clinical_cat[7]]] <- factor(spe[[clinical_cat[7]]], levels = c("healthy","early","late"))

# define color vectors
color_vectors <- list()
pheno_clusters_new <- setNames(c("#C4281C","#C2DAB8","#E8BAC8","#80BBDB","#C470A0","#0D69AC","#F5CD30","#287F47",
                                 "#A05F35","#D9856C","#6B327C","#008F9C","#C7D23C","#B7D7D5","#923978","#27462D",
                                 "#FF9494","#938767","#FFF67B","#E1A4C2","#FC7B1B","#CD6298","#102ADC"), 
                               as.character(unique(spe$pheno_clusters_new)))

indication <- setNames(c("#4DBBD533", "#E64B35AA"),
                       c(unique(colData(spe)$Disease)))

Donor <- setNames(c("#FFFF33", "#FFCC66",'#FF9933','#FF6633','#00FFFF','#FF0033','#79B5B5', '#C470A0',
                         '#996633','#999933','#99CC33','#FF9494', '#33FF33','#336633', '#330066','#923978'),
                       c(unique(colData(spe)$Donor)))

Neighbourhood_del_80_pheno_new <- setNames(c("#CC00CC", "#260EEC", "#FFCA28", "#004D40","#FF6633","#66FF66", 
                                             "#EF9EA7", "#990000", "#CC0033","#4FC3F7"),
                                           unique(spe$Neighbourhood_del_80_pheno_new))

color_vectors$clusters <- pheno_clusters_new
color_vectors$Disease <- indication
color_vectors$Donor <- Donor
color_vectors$neighbourhood_del_80_pheno_new <- Neighbourhood_del_80_pheno_new

color_vectors[[clinical_cat[2]]] <- setNames(c("#4DBBD533", "#C03830", "#F6BF93"), unique(spe[[clinical_cat[2]]]))
color_vectors[[clinical_cat[3]]] <- setNames(c("#4DBBD533","#377EB8","#4DAF4A"), unique(spe[[clinical_cat[3]]]))
color_vectors[[clinical_cat[4]]] <- setNames(c("#4DBBD533","#FC8D62","#8DA0CB"), unique(spe[[clinical_cat[4]]]))
color_vectors[[clinical_cat[5]]] <- setNames(c("#4DBBD533","#FFFFB3","#BEBADA"), unique(spe[[clinical_cat[5]]]))
color_vectors[[clinical_cat[6]]] <- setNames(c("#4DBBD533","#A6D854","#FFD92F"), unique(spe[[clinical_cat[6]]]))
color_vectors[[clinical_cat[7]]] <- setNames(c("#4DBBD533","#F781BF","#999999"), unique(spe[[clinical_cat[7]]]))

metadata(spe)$color_vectors <- color_vectors

```

# Aggregate by healthy and SSc

```{r aggreg, eval=TRUE, cache=TRUE}

# Filter for all Met-CNs
spe$CN_10_aggNbh_delaunay_80_new <- as.numeric(spe$CN_10_aggNbh_delaunay_80_new)
spe <- spe[,spe$CN_10_aggNbh_delaunay_80_new%in%c(4:10)]
spe$CN_10_aggNbh_delaunay_80_new <- as.factor(spe$CN_10_aggNbh_delaunay_80_new)

# Create subsetted spe objects for healthy and SSc
spe_healthy <- spe[,spe$Disease=="Healthy"]
spe_ssc <- spe[,spe$Disease=="SSc"]

# Aggregate across cells for healthy
patient_mean_all_cells_healthy <- aggregateAcrossCells(
  as(spe_healthy, "SingleCellExperiment"),
  ids = spe_healthy$CN_10_aggNbh_delaunay_80_new,
  statistics = "mean",
  use.assay.type = "z-rescaled",
  subset.row = rownames(spe_healthy)[rowData(spe_healthy)$use_channel_met_markers]
)

# Aggregate across cells for SSc
patient_mean_all_cells_ssc <- aggregateAcrossCells(
  as(spe_ssc, "SingleCellExperiment"),
  ids = spe_ssc$CN_10_aggNbh_delaunay_80_new,
  statistics = "mean",
  use.assay.type = "z-rescaled",
  subset.row = rownames(spe_ssc)[rowData(spe_ssc)$use_channel_met_markers]
)

# Aggregate across cells for all donors
patient_mean_all_cells_all <- aggregateAcrossCells(
  as(spe, "SingleCellExperiment"),
  ids = spe$CN_10_aggNbh_delaunay_80_new,
  statistics = "mean",
  use.assay.type = "z-rescaled",
  subset.row = rownames(spe)[rowData(spe)$use_channel_met_markers]
)

# Rename columns for cells number and Met-CN for all objects

names(colData(patient_mean_all_cells_healthy))[which(names(colData(patient_mean_all_cells_healthy)) ==
                                                       "ncells")] = "Cells_number"

names(colData(patient_mean_all_cells_healthy))[which(names(colData(patient_mean_all_cells_healthy)) ==
                                                       "CN_10_aggNbh_delaunay_80_new")] = "Met-CN"

names(colData(patient_mean_all_cells_ssc))[which(names(colData(patient_mean_all_cells_ssc)) ==
                                                   "ncells")] = "Cells_number"
names(colData(patient_mean_all_cells_ssc))[which(names(colData(patient_mean_all_cells_ssc)) ==
                                                   "CN_10_aggNbh_delaunay_80_new")] = "Met-CN"

names(colData(patient_mean_all_cells_all))[which(names(colData(patient_mean_all_cells_all)) == "ncells")] = "Cells_number"
names(colData(patient_mean_all_cells_all))[which(names(colData(patient_mean_all_cells_all)) == "CN_10_aggNbh_delaunay_80_new")] = "Met-CN"

```

# Heatmap z score rescaled - all cells {.tabset .tabset-pill}

```{r heatmap2, eval=TRUE, eval=TRUE, fig.width=5, fig.height=6, results='asis'}

cat('\n\n## Healthy \n')

dittoHeatmap(
  patient_mean_all_cells_healthy,
  genes = met_markers,
  assay = "z-rescaled",
  cluster_cols = TRUE,
  cluster_rows = FALSE,
  scale = "row",
  annot_col = c(""),
  annot.by = c("Met-CN")
)

cat('\n\n## SSc \n')

dittoHeatmap(
  patient_mean_all_cells_ssc,
  genes = met_markers,
  assay = "z-rescaled",
  cluster_cols = TRUE,
  cluster_rows = FALSE,
  scale = "row",
  annot_col = c(""),
  annot.by = c("Met-CN")
)

cat('\n\n## All donors \n')

dittoHeatmap(
  patient_mean_all_cells_all,
  genes = met_markers,
  assay = "z-rescaled",
  cluster_cols = TRUE,
  cluster_rows = FALSE,
  scale = "row",
  annot_col = c(""),
  annot.by = c("Met-CN")
)

```

# Outputs

This analysis generates the following results: <br>

1. Heatmap of marker expression across Met-CN. <br>

# Session information

```{r session, eval=TRUE}
etime <- proc.time() - ptm
cat('Rendering this document took :', etime[3], ' s \n')

sessioninfo::session_info()
```

