---
title: "Dotplot integrated dataset"
author: "Veda"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
source("data_preprocessing/common/config.R")
knitr::opts_chunk$set(echo = TRUE)
```

```{r library set up}
library(SingleCellExperiment)
library(SpatialExperiment)
library(DelayedMatrixStats)
library(dittoSeq)
library(ggsankey)
library(ggplot2)
library(dplyr)
library(viridis)
library(scuttle)
library(Seurat)
library(SpatialFeatureExperiment)
```

```{r load spe}
spe<-readRDS(project_path("Revision/Nan annotation/IMC_AnchorTrans_merged_251030163124.rds"))

sfe<-readRDS(project_path("Revision/Nan annotation/Data/Xenium sfe objects/Xenium sfe object/XeniumSfe_FibAnno_251104104458.rds"))

seurat<-readRDS(project_path("Revision/Nan annotation/Data/Xenium sfe objects/VedaSScSkinXe_EcFibAnno_260225234740.rds"))
```

```{r transfer_predicted_celltype, message=FALSE, warning=FALSE}

head(colnames(spe))
head(colData(sfe)$KEY)

# Create a lookup dataframe
df_map <- data.frame(
  KEY = colnames(spe),
  predicted.celltype = spe$predicted.celltype,
  stringsAsFactors = FALSE
)

# Align based on shared KEYs
idx <- match(colData(sfe)$KEY, df_map$KEY)

# Transfer the predicted.celltype column
colData(sfe)$predicted.celltype <- df_map$predicted.celltype[idx]
# Check a few transferred entries
head(colData(sfe)$predicted.celltype)

# Count how many matches were successful
sum(!is.na(colData(sfe)$predicted.celltype))
sum(is.na(colData(sfe)$predicted.celltype))

```

```{r dotplot}

genes_use_subset <- c(
  "CTHRC1","POSTN","FN1","COL1A1","COL1A2","COL8A1","SFRP4","SFRP2","FAP","LRRC15",
  "CCL19","CXCL12","APOE","PI16","LGR5","COL18A1","WIF1"
)



stromal_types <- c("stromal_1", "stromal_2", "stromal_3", "stromal_4", 
                   "stromal_5", "stromal_7", "stromal_8")
cur_sfe <- sfe[, sfe$predicted.celltype %in% stromal_types]


library(Seurat)


seurat_obj <- as.Seurat(
  cur_sfe,
  counts = "counts",
  data   = "logcounts"
)
unique(Idents(seurat_obj))
Idents(seurat_obj) <- "predicted.celltype"

# ✅ enforce stromal_1 ... stromal_8 order
Idents(seurat_obj) <- factor(Idents(seurat_obj), levels = stromal_types)


d<-DotPlot(
  object = subset(seurat_obj, idents = levels(Idents(seurat_obj))),
  features = genes_use_subset,
  col.min = 0.5,
  col.max = 2,
  dot.scale = 10
) +
  coord_flip() +
  labs(x = NULL, y = NULL) +

  RotatedAxis() +

  scale_color_gradientn(
    colors = rev(RColorBrewer::brewer.pal(7, "RdBu"))
  ) +

  scale_size_continuous(
    range  = c(0, 5),
    breaks = c(25, 50, 75, 100),
    labels = c("25", "50", "75", "100")
  ) +

  theme_bw() +

  theme(
    axis.text.x = element_text(size = 8, angle = 45, hjust = 1)
  )
d

```
```{r dotplot 2}
## --- Prepare data: only stromal_2, stromal_4, stromal_8 ---

keep_stromal <- c("stromal_2", "stromal_8")
#keep_stromal <- unique(seurat_obj$predicted.celltype)

Idents(seurat_obj) <- factor(
  seurat_obj$predicted.celltype,
  levels = keep_stromal
)

obj_sub <- subset(seurat_obj, idents = keep_stromal)


## --- Extract DotPlot data and manually row-scale gene expression ---

ddata <- DotPlot(obj_sub, features = genes_use_subset)$data

library(dplyr)

# Row-wise scaling (per gene)
ddata <- ddata %>%
  group_by(features.plot) %>%
  mutate(avg.exp.scaled = base::scale(avg.exp)[,1]) %>%
  ungroup()

# Ensure x-axis = stromal clusters in correct order
ddata$id <- factor(ddata$id, levels = keep_stromal)


## --- Final plot: x = clusters, y = genes ---

p <- ggplot(ddata, aes(x = id, y = features.plot)) +
  geom_point(aes(size = pct.exp, color = avg.exp.scaled)) +
  scale_color_gradientn(colors = rev(RColorBrewer::brewer.pal(7, "RdBu"))) +
  scale_size(range = c(1, 8)) +
  labs(x = NULL, y = NULL) +
  theme_bw() +
  theme(
    axis.text.x = element_text(size = 8, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 8)
  )

p


```