---
title: "Interaction analysis"
author: "Alex Matei"
date: "`r format(Sys.time(), '%Y-%m-%d')`"
output: 
  html_document: 
    toc: true
    toc_float: true
    toc_depth: 4
    df_print: paged
    code_folding: hide
---

# Setup
```{r setup, include=FALSE}
source("data_preprocessing/common/config.R")

library(here)
source("data_preprocessing/common/original_setup.R")

knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE, root.dir = here::here())
```

```{r timestamp}
ts <- format(Sys.time(), "%Y%m%d%H%M%S")
ptm <- proc.time()

cat("This document was created with the time stamp",ts)

```

```{r planfuture}

with_future <- FALSE

if(with_future){
plan_future_fx(memory_fraction = 0.8, handler = "txtprogressbar")
}

```

# Load spe

```{r load spe}
spe <- readRDS(here("Datasets/spe_20241027185617.rds"))

```

# Prepare spe for analysis

```{r prep spe}
# Create a new data frame with all the colData of the spe object - to recode the patient_id column

metadata <- colData(spe)

# add a new column to metadata called Donor where you recode the patient_id column
# the elements starting with NH should be called Healthy1, Healthy2, etc.
# the elements starting with SSc should be called SSc1, SSc2, etc.
metadata$Donor <- dplyr::recode(metadata$patient_id,
                                     Healthy1="Healthy1",
                                     Healthy2="Healthy2", 
                                     SSc1="SSc1",
                                     SSc2="SSc2",
                                     SSc3="SSc3",
                                     SSc4="SSc4",
                                     SSc5="SSc5",
                                     SSc6="SSc6",
                                     SSc7="SSc7",
                                     SSc8="SSc8",
                                     Healthy3="Healthy3",
                                     Healthy4="Healthy4",
                                     SSc9="SSc9",
                                     Healthy5="Healthy5",
                                     Healthy6="Healthy6",
                                     Healthy7="Healthy7")


metadata$Disease <- dplyr::recode(metadata$indication,
                                  NH="Healthy",
                                  SSc="SSc")

metadata$ILD <- dplyr::recode(metadata$ILD,
                                     healthy="healthy",
                                     "1"="ILD", 
                                     "0"="no ILD")

metadata$Arthritis[is.na(metadata$Arthritis)] <- "no arthritis"

# Assign the new column in metadata to the spe object
spe$Donor <- metadata$Donor
spe$ILD <- metadata$ILD
spe$Arthritis <- metadata$Arthritis
spe$Disease <- metadata$Disease

names(colData(spe))[which(names(colData(spe))=="Skin.progression.at.biopsy")]="Progression_skin"
names(colData(spe))[which(names(colData(spe))=="Subtype.(dc/lc)")]="Subtype_dc_lc"

met_markers <- c("Glut1",
                 "HK1",
                 "PFKL1",
                 "PKM2",
                 "LDHA",
                 "GAPDH",
                 "CS",
                 "OGDH",
                 "ATP5A",
                 "SDHA",
                 "CD98",
                 "ACAC",
                 "CPT1a",
                 "G6PD",
                 "p_mTOR",
                 "pAMPK",
                 "NOX4",
                 "HIF1a",
                 "PGC-1a",
                 "TFAM",
                 "NRF2_p")

glycolysis_markers <- c("Glut1",
                 "HK1",
                 "PFKL1",
                 "PKM2",
                 "LDHA",
                 "GAPDH")

no_met_markers <- setdiff(rownames(spe),met_markers) 
rowData(spe)$use_channel_met_markers <- rownames(spe) %in% met_markers
rowData(spe)$use_channel_glyc_markers <- rownames(spe) %in% glycolysis_markers

# define clinical categories
clinical_cat <- c("Disease","Progression_skin", "Arthritis", "DU.history", "ILD", "Subtype_dc_lc", "Early.or.not")

spe[[clinical_cat[1]]] <- factor(spe[[clinical_cat[1]]], levels = c("Healthy", "SSc"))
spe[[clinical_cat[2]]] <- factor(spe[[clinical_cat[2]]], levels = c("healthy", "progressive", "stable"))
spe[[clinical_cat[3]]] <- factor(spe[[clinical_cat[3]]], levels = c("healthy","arthritis","no arthritis"))
spe[[clinical_cat[4]]] <- factor(spe[[clinical_cat[4]]], levels = c("healthy","DU history","no DU history"))
spe[[clinical_cat[5]]] <- factor(spe[[clinical_cat[5]]], levels = c("healthy","ILD","no ILD"))
spe[[clinical_cat[6]]] <- factor(spe[[clinical_cat[6]]], levels = c("healthy","dcSSc","lcSSc"))
spe[[clinical_cat[7]]] <- factor(spe[[clinical_cat[7]]], levels = c("healthy","early","late"))

# define color vectors
color_vectors <- list()
pheno_clusters_new <- setNames(c("#C4281C","#C2DAB8","#E8BAC8","#80BBDB","#C470A0","#0D69AC","#F5CD30","#287F47",
                                 "#A05F35","#D9856C","#6B327C","#008F9C","#C7D23C","#B7D7D5","#923978","#27462D",
                                 "#FF9494","#938767","#FFF67B","#E1A4C2","#FC7B1B","#CD6298","#102ADC"), 
                               as.character(unique(spe$pheno_clusters_new)))

indication <- setNames(c("#4DBBD533", "#E64B35AA"),
                       c(unique(colData(spe)$Disease)))

Donor <- setNames(c("#FFFF33", "#FFCC66",'#FF9933','#FF6633','#00FFFF','#FF0033','#79B5B5', '#C470A0',
                         '#996633','#999933','#99CC33','#FF9494', '#33FF33','#336633', '#330066','#923978'),
                       c(unique(colData(spe)$Donor)))

Neighbourhood_del_80_pheno_new <- setNames(c("#CC00CC", "#260EEC", "#FFCA28", "#004D40","#FF6633","#66FF66", 
                                             "#EF9EA7", "#990000", "#CC0033","#4FC3F7"),
                                           unique(spe$Neighbourhood_del_80_pheno_new))

color_vectors$clusters <- pheno_clusters_new
color_vectors$Disease <- indication
color_vectors$Donor <- Donor
color_vectors$neighbourhood_del_80_pheno_new <- Neighbourhood_del_80_pheno_new

color_vectors[[clinical_cat[2]]] <- setNames(c("#4DBBD533", "#C03830", "#F6BF93"), unique(spe[[clinical_cat[2]]]))
color_vectors[[clinical_cat[3]]] <- setNames(c("#4DBBD533","#377EB8","#4DAF4A"), unique(spe[[clinical_cat[3]]]))
color_vectors[[clinical_cat[4]]] <- setNames(c("#4DBBD533","#FC8D62","#8DA0CB"), unique(spe[[clinical_cat[4]]]))
color_vectors[[clinical_cat[5]]] <- setNames(c("#4DBBD533","#FFFFB3","#BEBADA"), unique(spe[[clinical_cat[5]]]))
color_vectors[[clinical_cat[6]]] <- setNames(c("#4DBBD533","#A6D854","#FFD92F"), unique(spe[[clinical_cat[6]]]))
color_vectors[[clinical_cat[7]]] <- setNames(c("#4DBBD533","#F781BF","#999999"), unique(spe[[clinical_cat[7]]]))

metadata(spe)$colors_vectors$Progression_skin <- setNames(c("#6CC3F4", "#C03830", "#F6BF93"),
                                                          unique(spe$Progression_skin))

metadata(spe)$color_vectors <- color_vectors

rm(metadata)

unique(spe$pheno_clusters_new)

spe$pheno_clusters_new2 <- case_when(
  grepl("CD45_CD3",spe$pheno_clusters_new) ~ "CD45",
  TRUE ~ spe$pheno_clusters_new
)

unique(spe$pheno_clusters_new2)
```


# Test interactions 

```{r test interactions, cache=TRUE}

number_repeat_interaction <- 2
subset_spe <- TRUE
subset_variable <- "Disease"
group_by <- "sample_id"
label <- "pheno_clusters_new"
colPairName <- "delaunay_80_new"

interaction_test_name <- paste0("interaction_test_", number_repeat_interaction)
if (subset_spe) {
  if (with_future) {
    with_progress({
      p <- progressor(along = unique(spe[[subset_variable]]))
      # Apply the function to each unique value of Skin.progression.at.biopsy
      interaction_list <- future_lapply(unique(spe[[subset_variable]]), function(value_to_subset) {
        p()  # Update progress
        process_interaction_fx(
          spe,
          subset = TRUE,
          subset_variable = subset_variable,
          subset_value = value_to_subset,
          group_by = group_by,
          label = label,
          colPairName = colPairName
        )
      })
    })
  } else {
    interaction_list <- lapply(unique(spe[[subset_variable]]), function(value_to_subset) {
      process_interaction_fx(
        spe,
        subset = TRUE,
        subset_variable = subset_variable,
        subset_value = value_to_subset,
        group_by = group_by,
        label = label,
        colPairName = colPairName
      )
    })
  }
  
  # Combine all results into a single data frame
  interaction_all <- do.call(rbind, interaction_list)
  
  interaction_all <- data.frame(interaction_all)
  
  metadata(spe)[[interaction_test_name]]$params$subset <- TRUE
  metadata(spe)[[interaction_test_name]]$params$subset_variable <- subset_variable
  metadata(spe)[[interaction_test_name]]$results <- interaction_all
} else{
  interaction_all <- process_interaction_fx(
    spe,
    subset = FALSE,
    group_by = group_by,
    label = label,
    colPairName = colPairName
  )
  metadata(spe)[[interaction_test_name]]$params$subset <- FALSE
  metadata(spe)[[interaction_test_name]]$results <- interaction_all
}

head(metadata(spe)[[interaction_test_name]]$results)

```


# Save the spe

```{r save spe}

output_dir <- here("Datasets/")
output_spe_filename <- paste0("spe_",ts, ".rds")
saveRDS(spe, file.path(output_dir, output_spe_filename))

```

# Outputs

This analysis generates the following results: <br>

1. It performs interaction tests and saves them in metadata(spe)$interaction_test$results. 
2. It saves the spe with the interaction tests results at '`r paste0(output_dir, output_spe_filename, sep="")`'. <br>

# Session information

```{r session, eval=TRUE}
etime <- proc.time() - ptm
cat('Rendering this document took :', etime[3], ' s \n')

sessioninfo::session_info()
```
