---
title: "resolvi prep"
author: "Yi-Nan Li"
date: "`r Sys.Date()`"
output: 
   html_document:
    toc: true
    toc_float: true
    df_print: paged
    code_folding: hide
    theme: bootstrap
    wrap: 72
---


```{r setup, include=FALSE}
source("data_preprocessing/common/config.R")
knitr::opts_chunk$set(echo = TRUE, message = FALSE)

## set working directory for CLI rendering
```


```{r conda}
tryCatch({
  reticulate::use_condaenv(paste0(project_path("external/"), "/"))
  reticulate::py_config()
}, error = function(e){
  message('Error setting up python env: ', e$message)
  quit(status =1)
})
```


```{r ts}
ptm <- proc.time()
tstamp <- format(Sys.time(), '%y%m%d%H%M%S')

```
  
This document is generated with the timestamp ``r tstamp``.


## Aim

Generate AnnData for resolvi.  

## Data

Load object from Meilin from `2025-11-11`. 

  
```{r data}
library(Seurat)
library(tidyverse)

obj <- readRDS('../data/20251111mergedqcdata1.rds')

obj@meta.data$SlideId <- paste0('00', gsub('.000000', '', as.character(obj$SlideId)))
obj@meta.data$SlideId <- case_when(
  !is.na(obj$XeniumSlideId) ~ obj$XeniumSlideId,
  obj$SampleId %in% c(Sys.getenv("METABOLIC_ADDITIONAL_XENIUM_SAMPLE", unset = "AdditionalValidation1")) ~ '0037406',
  .default = obj$SlideId
)

obj <- JoinLayers(obj)
obj <- UpdateSeuratObject(obj)
                                      
coords <- lapply(Images(obj), function(i){
  GetTissueCoordinates(obj, i)
})
coords <- do.call(rbind, coords)
coords <- column_to_rownames(coords, 'cell') %>% .[colnames(obj),]

identical(colnames(obj), rownames(coords))
```


## Anndata
  
```{r anndata}
library(anndataR)
library(reticulate)

tmp <- CreateSeuratObject(obj[['Xenium']]['counts'],
                     meta.data = dplyr::select(obj[[]], c('SampleId', 'SlideId', 'ROI')))
colnames(coords) <- NULL
Spatial <- CreateDimReducObject(embeddings = as.matrix(coords), key = 'coord_')
tmp[['X_spatial']] <- Spatial



```



## Export

```{r export}
write_h5ad(tmp, paste0('../data/MeilinXenium_251111_', tstamp, '.h5ad'))
```




## Session information
```{r session}
etm <- proc.time() - ptm
cat('This analysis took :', etm[3], 's \n')
sessioninfo::session_info()
```



```{bash render, eval = FALSE}
Rscript -e "rmarkdown::render('~/projects/2025_xenium_SScBite/scripts/20251118_ResolviPrep.Rmd', output_file = '../analysis/ResolViPrep_$(date +"%Y%m%d_%H%M%S").html')" > ~/projects/2025_xenium_SScBite/logs/resolvi_$(date +"%Y%m%d_%H%M%S").log 2>&1
```
